#Format [ 
#         [[section1 list1], [section1 list2]
#         [[section2 list1], [section2 list2]
#       ]
# list = [identifier, title, type, range, help_text, default_value, mandatory]
#     identifier: 2-character code
#     title: title of the code, used to show user for DFlash application
#     type: data type expected/needed
#     range: None, ("length", value), ("set", value1, value2, ... , valueN), ("range", min, max, units), ("units", unit)
#     help_text: text describing the data
#     value: default value for the data 
#     mandatory: boolean determining whether the field is mandatory or not
# Modified by W. Kempton, 30 Mar 2017

evse_index = [["EVSE Factory Settings", 0],
              ["EVSE Electrical", 3],
              ["EVSE Power Limits", 4],
              ["EVSE Network Data", 5],
              ["EVSE Other", 6]]

#access: evse[page][field][info]

evse = [
    #EVSE Factory Settings
    [["sn",
         "Serial Number",
         str,
         None,
         "Serial number, unique to this device",
         None,
         False],
    ["ma",
         "Manufacturer Name",
         str,
         None,
         "EVSE Manufacturer Name",
         None,
         True],
    ["mo",
         "Model Name",
         str,
         None,
         "EVSE Model Name or number",
         None,
         True],
    ["pn",
         "Part Number",
         str,
         None,
         "Part Number or SKU of this model; give only base number if trailing digits are minor variants not affecting operation (e.g. for color)",
         None,
         False],
    ["hv",
         "Hardware Version",
         str,
         None,
         "Hardware version of EVSE, revision number or version number of this model",
         None,
         False],
    ["vv",
         "VEL Version",
         str,
         None,
         "VEL version and variant, e.g. vv52b_0 (vel 5.2b, variant 0 is for EVSE)",
         None,
         False],
    ["cn",
         "Connector type",
         str,
         None,
         "Expecting J1772 or CHAdeMO orIEC62196-2 or IEC62196-2-caseB (note CaseB=detachable, caseC=permanent attachment to EVSE; if no case is given, caseC is our default)",
         None,
         False],
    ["ph",
         "Phase Capability of connector(s)",
         str,
         ("set", 'D', '1', '3'),
         "Phase of connector should be 1 or 3, or D for DC",
         None,
         True],
    ["dm", 
         "Maximum connector & EVSE current, as built",
          int,
         ("range", 0, 255),
         "Maximum current through EVSE and connector, as built and tested",
         None,
         True],
    ["bm", 
         "Built-in meter Type (if any))",
         str,
         ("set", 'NOT-PRESENT', 'UD-B', 'UD-C','EKM-25-v.2', 'EKM-Omni v.3'),
         "Meter built in at factory. UD meter on RCD board is 'UD-B'. Use 'NOT-PRESENT' if none",
         None,
         True],
    ["gf", 
         "GIV Dispatch Flags",
         int,
         ("range", 0, 255),
         "GIV Dispatch Flags",
         145,
         True]     
    ],
#EVSE Electrical
    [["eb",
         "Electrician Badge",
         str,
         ("length", 32),
         "The id or badge of the electrical inspector entering these values",
         None,
         False],
    # ["ad",
    #      "Address",
    #      str,
    #      ("length", 128),
    #      "The postal address of this EVSE",
    #      None,
    #      False],
    ["ad1",
         "Address Line 1",
         str,
         None,
         "Address line 1 of the postal address of this EVSE",
         None,
         False],
    ["ad2",
         "Address Line 2",
         str,
         None,
         "Address line 2 of the postal address of this EVSE",
         None,
         False],
    ["ad3",
         "City",
         str,
         None,
         "City of the postal address of this EVSE",
         None,
         False],
    ["ad4",
         "State",
         str,
         None,
         "State of the postal address of this EVSE",
         None,
         False],
    ["ad5",
         "Zip Code",
         str,
         None,
         "Zip Code of the postal address of this EVSE",
         None,
         False],
    ["ad6",
         "Country",
         str,
         None,
         "Country of the postal address of this EVSE",
         None,
         False],
    ["ui",
         "Utility ID",
         str,
         ("length", 32),
         "The DSO id of the load-serving entity, in US find these under EIA-861 data files, 'File1', which is updated yearly.",
         None,
         False],
    ["un",
         "Utility or DSO Name",
         str,
         ("length", 128),
         "Electric utility or DSO short name",
         None,
         False],
    ["so",
         "System Operator",
         str,
         ("length", 32),
         "Name of the TSO or ISO (e.g. PJM, ERCOT, CalISO, Energinet.dk, etc.)",
         None,
         False],
    ["po",
         "Pole ID",
         str,
         ("length", 32),
         "US: Pole or connection nearest to this service drop. DK: Aftager Nr.",
         None,
         False],
    ["ts",
         "Transformer Serial Number",
         str,
         ("length", 32),
         "Nearest transformer to this EVSE circuit (may be utility or customer owned)",
         None,
         False],
    ["tp",
         "Transformer Power Rating",
         int,
         ("range", 0, 10000),
         "The rated kVA of the nearest transformer",
         None,
         False],
    ["df",
         "Distribution Feeder",
         str,
         ("length", 128),
         "The name of ID used by the local utility for the medium voltage supply",
         None,
         False],
    ["sb",
         "Substation Name",
         str,
         ("length", 128),
         "Substation name, id, or number",
         None,
         False],
    ["si",
        "Service Drop Meter Serial Number",
        str,
        ("length", 32),
        "Utility meter number for building or site",
        None,
        False],
    ["bi",
         "Submeter id",
         str,
         ("length", 32),
         "May be a label or a serial number, optional, but if >1 EVESE on this submeter, then 'bi' required for all and must be identical for all",
         None,
         False],
    ["pa",
         "Panel Amperes",
         int,
         ("range", 0, 10000),
         "Breaker amps for the whole panel in which the EVSE is wired. For residential, this is typically the service drop amp capacity",
         None,
         False],
    ["pl",
         "Panel Label",
         str,
         ("length", 32),
         "The label on the panel, required only if multiple panels in building",
         None,
         False],
    ["ca",
         "Circuit Amperes",
         int,
         ("range", 0, 1000),
         "Nominal circuit breaker amperes for the circuit with this EVSE",
         None,
         False],
    ["cl",
         "Circuit Label",
         str,
         ("length", 32),
         "the number (or other label if present) for the breaker feeding this EVSE.  If only one EVSE per circuit, this is an optional assist for service, BUIT if one breaker has >1 EVSE, it is requred that all EVSEs have 'cl' and that all are exactly matching strings",
         None,
         False],
    ["vo",
         "Voltage Nominal",
         int,
         ("range", 0, 600),
         "Nominal voltage for the circuit feeding the EVSE.  Critical setting, used to set backfeeding target voltage",
         None,
         False],
    ["rf",
         "Reverse Feeding Permit",
         str,
         ("set", '1', '0', '01', '00'),
         "Whether this EVSE has interconnect permit to send power back to the grid, 1 means true, 0 prohibits reverse flow",
         None,
         False],
    ["mt",
         "Meter Type",
         str,
         ("set", "NOT-PRESENT", "UD-B", "EKM-25 v.2", "EKM-Omni v.3", "EKM-Omni v.4", "EKM-Omni v.4-3ph", "ms" ),
         "The type of meter in the EVSE, if different from mT as manufactured.",     # "Defined previously: 'EKM-25 v.2', 'EKM-Omni v.4', 'ms', 'UD' ",
         None,
         False],
    ["ms",
         "Meter Serial Number",
         str,
         None,
         "Serial number of internal EVSE meter, or, UD meter in EVSE-B single will assume EVSE serial#, if dual hose append -A or -B (?)",
         None,
         False],
    ["ct",
         "Version of configuration (DFlash) program",
         str,
        ("length", 32),
         "Version of configureation or 'DFlash' tool writing these (auto filled in)",
         None,
         False]
    ],
#EVSE Power Limits
    [["mc",
         "Maximum Charge-Rate",
         int,
         ("range", 0, 255),
         "The maximum charge rate in amperes of this EVSE",
         "0",
         False],
     ["fc",
        "Floor Charge-Rate",
         int,
         None,
         "The minimum charge rate in amperes of this EVSE",
         None,
         False],
    ["md",
         "Maximum Discharge-Rate",
         int,
         None,
        "The maximum discharge rate in amperes of this EVSE",
         None,
        False],
    ["fd",
         "Floor Discharge-Rate",
         int,
         None,
         "The minimum discharge rate in amperes of this EVSE",
         None,
         False],     
    ["ot",
         "Overcurrent trip (% of mc/md)",
         int,
          ("range", 102, 200),
         "Default is relay opens at 112% of max(mc,md) to prevent buiolding breaker trip; set only if it should open at a different current",
         "102",
         False]
# following were specific to UD motor Pool, two EVSE on one circuit, now deleted
#    ["dc",
#         "Default Charge-Rate",
#         int,
#         None,
#         "The default charge rate in amperes of this EVSE",
#         None,
#         False],
#    ["dd",
#         "Default Discharge-Rate",
#         int,
#         None,
#         "The default discharge rate in amperes of this EVSE",
#         None,
#         False]
    ],
#EVSE Network Data
    [["hn",
         "Hostname of Aggregator",
         str,
         ("length", 128),
         "format: EVSE_SERIAL.evse.TSO.nuvve.info, where SERIAL and TSO are the values that must be changed",
         None,
         True],
#    ["ub",
#         "URI of Backup aggregator",
#         str,
#         ("length", 128),
#         "Try this URI if 'ua' fails. Can be used wordwide.",
#          "https://aeolus.ceoe.udel.edu",
#         False],
#   ["uc",
#         "URI of OCCP server",
#         str,
#         ("length", 128),
#         "If present, this supercedes value in code",
#         None,
#         False],
    ["ip",
         "EVSE IP Address (*=DHCP)",
         str,
         ("length", 64),
         "IP Address of this EVSE if site service requires a static IP; if missing or ip*, use DHCP",
         None,
         False],
    ["su",
         "Subnet Mask",
         str,
         ("length", 64),
         "Subnet mask (su, gw and dn are present only if not DHCP",
         None,
         False],
    ["gw",
         "Gateway",
         str,
         ("length", 64),
         "Gateway",
         None,
         False],
    ["dn",
         "DNS list",
         str,
         ("length", 256),
         "DNS list, with IP's separated by semi-colons, e.g. dn128.175.74.219;128.175.24.84",
         None,
         False]
    ],
#EVSE Other
    [["en",
         "EVSE Name",
         str,
         ("length", 32),
         "A name, number or label written on this EVSE and visible to user. If not label, ask user what makes sense to call it. This should be unique within the building or parking lot.",
         None,
         False],
    ["la",
         "Latitude",
         str,
         ("length", 32),
         "The GPS latitude of this EVSE, decimal format",
         None,
         True],
    ["lo",
         "Longitude",
         str,
         ("length", 32),
         "The GPS longitude of this EVSE, decimal format",
         None,
         True],
    ["ga",
         "GPS Altitude, in integer meters",
         int,
         ("range", 0, 9000),   
         "The GPS Altitude in m above Sea level (enter 0 if negative)",
         None,
         False],
    ["sp", 
         "Sharing permissions",
         str,
         ("set", 'private', 'public','fleet'),
         "Who is allowed to see this EVSE on maps and see charge rate? (ask EVSE user/owner if uncertain)",
         None,
         False],
#  deprecated "on"
#    ["on",
#        "Owner Name for login",
#         str,
#         None,
#         "Default login name for initial registration of this EVSE",
#         None,
#         False],
    ["nt",
         "Note",
         str,
         ("length", 128),
         "Additional field, should show on info screen or field device; may be truncated",
         None,
         False]
    ]
]
