#Format [  
#         [(section1 list1), (section1 list2)]
#         [(section2 list1), (section2 list2)]
#       ]
# list = [identifier, title, type, range, help_text, default_value]
#     identifier: 2-character code
#     title: title of the code
#     type: data type expected/needed
#     range: 2-item tuple, (minimum, maximum)
#     help_text: text describing the data
#     default_value: default value for the data
#     mandatory: boolean determining whether the field is mandatory or not
ev_1_index = [("EV Page 0", 'ff'), ("EV Info", 2)]

ev_1 = [
    #EV Page 0
    [["sn",
         "Serial Number",
         str,
         None,
         "Serial number of the VSL, unique to this device suggested for UD: UDV0001, UDV0002, etc (UDV for VSL or Vehicle not to confuse with EVSE VELs)",
         None,
         False],
    ["vv",
         "VEL Version",
         str,
         None,
         "VEL version and variant, example vv52b_1",
         "5.2b_1",
         False]
    ],
#EV Info
    [["vn",
         "VIN Number",
         str,
         ("length", 20),
         "Not needed if Canbus interface gives VIN to VSL on demand",
         None,
         False],
    ["id",
         "Unique EV Identifier",
         str,
         None,
         "May not be needed is available, however, a separate unique ID may be provided here",
         None,
         False],
    ["ma",
         "Make",
         str,
         ("length", 20),
         "Manufacturer of the car",
         None,
         False],
    ["mo",
         "Model",
         str,
         ("length", 20),
         "Model name of the car",
         None,
         False],
    ["uf",
         "Upfitter",
         str,
         None,
         "Upfitter or car modifying company name, e.g. 'Autoport'",
         None,
         False],
    ["cn",
         "Connector Inlet",
         str,
         None,
         "e.g. J1772 or IEC62196-2",
         None,
         False],
    ["mc",
         "Maximum Charge Rate of Car",
         int,
         ("range", 0, 1000),
         "Maximum charge rate of car in amperes (minimum of inlet, cable, carger/PEU, etc.)",
         None,
         False],
    ["md",
         "Maximum Discharge Rate of Car",
         int,
         ("range", 0, 1000),
         "Maximum discharge rate in amperes, zero if cannot discharge",
         None,
         False],
    ["bk",
         "Battery kWh",
         int,
         ("range", 0, 10000),
         "Maximum usable capacity of battery in kWh",
         None,
         False],
    ["mr",
         "Maximum Range",
         int,
         ("range", 0, 500),
         "Maximum range in miles to use if calculation not available (may be depreciated when VSL starts calculating range)",
         None,
         False],
     # ["ai",
     #     "Anti-Islanding",
     #     str,
     #     ("length", 128),
     #     "Anti-islanding certified: 0 = not certified or tested, 1 = tested but no certificate, n = certificate number",
     #     None,
     #     False],
     ["lp",
         "Low Power",
         "hex",
         None,
         "A cut-off voltage for the 12V battery below which the VEL board will switch off",
         None,
         False],
    ["gf",
         "GIV Dispatch Flags",
         "hex",
         ("set", "00", "01", "02", "03", "04", "05", "06", "07"),
         """A set of flags that control dispatch while grid integrated:
         01 ANTI-ISLANDED
	 02 DISABLE_CHARGING_DISPATCH
	 04 DISABLE_DISCHARGING_DISPATCH
	 Set to 06 to disable charging and discharging.
         """,
         "00",
         False],
    ],
]
